### ISSUE TITLE
stuck on binz files.

### ISSUE THREAD

**Issue by DLewis01** [roro08/Sketchfab-Ripper#2]
version 1.17.3

UI is stuck in the progress bar on "Dumping .binz files"

Logs show 
[Info] Successfully downloaded model data.
[Info] Progress: Dumping .binz files...

Log-binzDumper show:
[Info] Downloading model info...
[Info] Starting a new Chrome process...
[Info] Waiting for Chrome to exit...
[Info] Waiting for Chrome to exit...
[Info] Waiting for Chrome to exit...
[Info] Waiting for Chrome to exit...
[Info] Waiting for Chrome to exit...

**Comment by Hombresinombre** [comment]
Update to 1.18, and check if your antivirus have deleted the plugins files

**Comment by DLewis01** [comment]
updated to 1.18, but have other issues with it, opened on https://github.com/roro08/Sketchfab-Ripper/issues/3

**Comment by DLewis01** [comment]
requires win 10+

**Comment by DLewis01** [comment]
requires win 10+
