### ISSUE TITLE
How do I fix a mapping error?

### ISSUE THREAD

**Issue by KaWah1222** [roro08/Sketchfab-Ripper#24]
Please help me, thank you!
![image](https://user-images.githubusercontent.com/51141646/169028879-0ae776bc-5550-44e5-9be5-64bdda98545f.png)
![image](https://user-images.githubusercontent.com/51141646/169029102-b410b4da-c49e-4367-a4dc-e89da5569fa3.png)

**Comment by moumouh206** [comment]
@KaWah1222  the texture are encrypted and no actual fix for that , the only this that you can do is to extract the textures manually using Firefox/chrome ( [https://spector.babylonjs.com/](url) ) extension called spector.js
here is a quick tutorial : https://www.youtube.com/watch?v=klttU44JAfQ

**Comment by KaWah1222** [comment]
> @KaWah1222 纹理是加密的，没有实际的修复，唯一要做的就是使用名为spector.js的Firefox/chrome（ [https://spector.babylonjs.com/](url)
> ）扩展手动提取纹理， 这是一个快速教程：[https ://www.youtube.com/watch?v=klttU44JAfQ](https://www.youtube.com/watch?v=klttU44JAfQ)

**Comment by KaWah1222** [comment]
> @KaWah1222 the texture are encrypted and no actual fix for that , the only thing to do is to extract the textures manually using Firefox/chrome ( [https://spector.babylonjs.com/](url) ) extension called spector.js
> here is a quick tutorial : https://www.youtube.com/watch?v=klttU44JAfQ

Thanks for your help, I will find some free time to try it out

**Comment by KaWah1222** [comment]
> @KaWah1222 the texture are encrypted and no actual fix for that , the only thing to do is to extract the textures manually using Firefox/chrome ( [https://spector.babylonjs.com/](url) ) extension called spector.js here is a quick tutorial : https://www.youtube.com/watch?v=klttU44JAfQ

Thanks again for your help, I can only download the low resolution mapping and I tried the method in the video and it doesn't load anything, which is bugging me, looking forward to your reply, thanks

**Comment by moumouh206** [comment]
@KaWah1222 With model ? Could you give me the link ?

**Comment by KaWah1222** [comment]
> @KaWah1222 With model ? Could you give me the link ?

Of course you can, the link is: https://sketchfab.com/3d-models/mercedes-benz-sprinter-ambulance-167097641f1f4021a15b7449bf8c25bf

**Comment by moumouh206** [comment]
@KaWah1222 first, I'm sorry it took too long, I'm at work and I have a slow PC and your textures are in 4K, so you know what that means
I extracted all the textures except the normals and the glass has no texture
[https://mega.nz/file/kI1ynBQR#d0jahOiMM9ca49vVQWnXzNnKJ9vXgMHEsS7cGx12O7g](url)

**Comment by KaWah1222** [comment]
> @KaWah1222 first, I'm sorry it took too long, I'm at work and I have a slow PC and your textures are in 4K, so you know what that means
> I extracted all the textures except the normals and the glass has no texture
> https://mega.nz/file/kI1ynBQR#d0jahOiMM9ca49vVQWnXzNnKJ9vXgMHEsS7cGx12O7g

No matter, anyway I want to thank you, I just tried another model, it can fully extract the texture, but I can not extract this model I told you, which makes me wonder if I did not operate properly, after all, I also just use this plug-in, I will download your extracted content later, thank you again for your enthusiastic help, ❤️

**Comment by KaWah1222** [comment]
> @KaWah1222 here, I added the normals https://mega.nz/file/UY8HVIKb#uciyZs-gYZY4kkxJ-Bh5rcdBu3FhhB36fXj-66bP5O4

thank you for your help

**Comment by KaWah1222** [comment]
> @KaWah1222 在这里，我添加了法线https://mega.nz/file/UY8HVIKb#uciyZs-gYZY4kkxJ-Bh5rcdBu3FhhB36fXj-66bP5O4



> @KaWah1222 here, I added the normals https://mega.nz/file/UY8HVIKb#uciyZs-gYZY4kkxJ-Bh5rcdBu3FhhB36fXj-66bP5O4

I'm sorry to bother you again, I've been trying to extract some new models recently, but after extracting the model it's mapping is wrong, I tried to fix it but it ended up missing a part, I remembered the last time you extracted the car mapping for me and it was perfect, here I'd like to ask you how you managed to do it without messing up the mapping? This is very important to me, thanks!
![image](https://user-images.githubusercontent.com/51141646/170809334-3a3f97d4-d006-4c32-8605-0ce11f5fd709.png)
![image](https://user-images.githubusercontent.com/51141646/170809349-db24db13-90a8-4523-a9f1-03a4f836522a.png)

**Comment by KaWah1222** [comment]
> @KaWah1222 here, I added the normals https://mega.nz/file/UY8HVIKb#uciyZs-gYZY4kkxJ-Bh5rcdBu3FhhB36fXj-66bP5O4

I'm sorry to bother you again, I've been trying to extract some new models recently, but after extracting the model it's mapping is wrong, I tried to fix it but it ended up missing a part, I remembered the last time you extracted the car mapping for me and it was perfect, here I'd like to ask you how you managed to do it without messing up the mapping? This is very important to me, thanks!
![image](https://user-images.githubusercontent.com/51141646/170809385-edde8936-34ad-4948-bd49-0723c5a695be.png)
![image](https://user-images.githubusercontent.com/51141646/170809394-b9093255-a8b0-4dfb-9769-9c678eae2674.png)

**Comment by moumouh206** [comment]
> > @KaWah1222 here, I added the normals https://mega.nz/file/UY8HVIKb#uciyZs-gYZY4kkxJ-Bh5rcdBu3FhhB36fXj-66bP5O4
> 
> I'm sorry to bother you again, I've been trying to extract some new models recently, but after extracting the model it's mapping is wrong, I tried to fix it but it ended up missing a part, I remembered the last time you extracted the car mapping for me and it was perfect, here I'd like to ask you how you managed to do it without messing up the mapping? This is very important to me, thanks! ![image](https://user-images.githubusercontent.com/51141646/170809385-edde8936-34ad-4948-bd49-0723c5a695be.png) ![image](https://user-images.githubusercontent.com/51141646/170809394-b9093255-a8b0-4dfb-9769-9c678eae2674.png)

Can you give me the link please

**Comment by KaWah1222** [comment]
> > > @KaWah1222 here, I added the normals https://mega.nz/file/UY8HVIKb#uciyZs-gYZY4kkxJ-Bh5rcdBu3FhhB36fXj-66bP5O4
> > 
> > 
> > I'm sorry to bother you again, I've been trying to extract some new models recently, but after extracting the model it's mapping is wrong, I tried to fix it but it ended up missing a part, I remembered the last time you extracted the car mapping for me and it was perfect, here I'd like to ask you how you managed to do it without messing up the mapping? This is very important to me, thanks! ![image](https://user-images.githubusercontent.com/51141646/170809385-edde8936-34ad-4948-bd49-0723c5a695be.png) ![image](https://user-images.githubusercontent.com/51141646/170809394-b9093255-a8b0-4dfb-9769-9c678eae2674.png)
> 
> Can you give me the link please

Of course , here's the link: https://sketchfab.com/3d-models/new-york-times-square-broadway-7th-ave-a46423fe8cfa4693ad51f116905b279f

But it took me a whole day of fiddling to get the textures to be less messy, Wah took too long to fix the textures I think it's too inefficient, I might I'm not very familiar with the regular operation of fixing textures, the tool I use is spector.js, so here I'd like to ask you how to fix these textures quickly. Looking forward to your reply, thanks again!

**Comment by moumouh206** [comment]
![Sans titre](https://user-images.githubusercontent.com/9859709/170860446-0a79310c-7157-407a-962f-f0b4d6c13e89.png)

@KaWah1222 you need to follow the numbers in the image, tho I think this model doesn't have normals, if you look at normals list, it said no texture, but it has Emission textures and base texture.
If you couldn't extract them, tell me

**Comment by KaWah1222** [comment]
> ![Sans titre](https://user-images.githubusercontent.com/9859709/170860446-0a79310c-7157-407a-962f-f0b4d6c13e89.png)
> 
> @KaWah1222 you need to follow the numbers in the image, tho I think this model doesn't have normals, if you look at normals list, it said no texture, but it has Emission textures and base texture. If you couldn't extract them, tell me

Thanks for your help, I've restored the full texture for now, I'm not sure if there are still flaws, but it looks perfect for now, but this did take me a lot of time to figure out, thanks for your help and answers.
